version: '3.7'

services:
  nginx :
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "9001:9001"
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    env_file:
      - .env