version: '3.8'

services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    container_name: nginx
    image: nginx:13.37
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/
    networks:
      - lanternite

  wordpress:
    build: ./requirements/wordpress/
    env_file:
      - .env
    container_name: wordpress
    volumes:
      - wordpress:/var/www/
    depends_on:
      - mariadb
    networks:
      - lanternite
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:10.5
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - lanternite

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/mamazzal/data/wordpress
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/mamazzal/data/mariadb

networks:
  lanternite:
    driver: bridge