version: '3.8'

services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www

  wordpress:
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/mamazzal/data/wordpress
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/mamazzal/data/mariadb