#!/bin/bash

COLOR_YELLOW='\033[1;33m'
COLOR_RESET='\033[0m'
 
#'%' is a wildcard that matches any host, 0.0.0.0

mariadbd --user=mysql --bootstrap << EOF
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ADMIN_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_USER_NAME}'@'%' IDENTIFIED BY '${MYSQL_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER_NAME}'@'%';
FLUSH PRIVILEGES;
EOF

echo -e "📖 ${COLOR_YELLOW}ALL DONE ${COLOR_RESET}"
exec "$@"